# Create Jenkins Environment 
# Add Maven 
# Add Git 
# Add Java 

# Fetch Image from DockerHub 
FROM ubuntu:16.04

# Install Package 
RUN apt-get update 
RUN apt-get install -y wget

# Download Maven 

RUN wget --no-verbose -O /tmp/apache-maven-3.2.2.tar.gz http://archive.apache.org/dist/maven/maven-3/3.2.2/binaries/apache-maven-3.2.2-bin.tar.gz

