---
dependencies: []

galaxy_info:
  author: Faisal Nizam
  description: Java for Linux
  company: "Noon"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Fedora
      versions:
      - all
  galaxy_tags:
    - development
    - system
    - web
